namespace BudganInfra.Repositories.AccountRecurringTransaction.GetTransactionsByAccount;

public interface IGetTransactionsByAccountRecurringRepoOp : IRepositoryOperationWithResultValue<List<DaoAccountTransactionByRecurring>>
{
}
