namespace BudganInfra.Repositories.AccountTransaction.GetCountByAccount;

public interface IGetCountAccountTransactionByAccountRepoOp : IRepositoryOperationWithResultValue<DaoGetCountAccountTransaction>
{
}
