import { describe, expect, test } from 'vitest'
import { CsvContentExtractor } from './csv-content-extractor'

describe('CsvContentExtractor', () => {
  test('detects comma delimiter and header row after noise lines', () => {
    const csvContent = [
      'Generated by test export',
      'Do not import this line',
      'Date,Description,Amount',
      '2024-01-01,Coffee,-4.20',
      '2024-01-02,Salary,1200.00'
    ].join('\n')

    const analyzer = new CsvContentExtractor()
    const result = analyzer.analyze(csvContent)

    expect(result.delimiter).toBe(',')
    expect(result.headerRowIndex).toBe(2)
    expect(result.header).toEqual(['date', 'description', 'amount'])
    expect(result.rows).toEqual([
      { date: '2024-01-01', description: 'Coffee', amount: '-4.20' },
      { date: '2024-01-02', description: 'Salary', amount: '1200.00' }
    ])
  })

  test('detects semicolon delimiter and supports quoted values', () => {
    const csvContent = [
      'Date;Description;Amount',
      '2024-02-01;"Market; Grocery";-87.54',
      '2024-02-02;"Dinner";-31.40'
    ].join('\n')

    const analyzer = new CsvContentExtractor()
    const result = analyzer.analyze(csvContent)

    expect(result.delimiter).toBe(';')
    expect(result.headerRowIndex).toBe(0)
    expect(result.rows).toEqual([
      { date: '2024-02-01', description: 'Market; Grocery', amount: '-87.54' },
      { date: '2024-02-02', description: 'Dinner', amount: '-31.40' }
    ])
  })
})
