namespace BudganInfra.Repositories.AccountRecurringTransaction.GetListByAccount;

public interface IListAccountRecurringTransactionByAccountRepoOp : IRepositoryOperationWithResultValue<List<DaoListAccountRecurringTransactionByAccount>>
{
}
