namespace BudganInfra.Repositories.AccountRecurringTransaction.GetList;

public interface IListAccountRecurringTransactionRepoOp : IRepositoryOperationWithResultValue<List<DaoListAccountRecurringTransaction>>
{
}
