namespace BudganInfra.Repositories.AccountTransaction.GetSnapshot;

public interface IGetSnapshotAccountTransactionByAccountRepoOp : IRepositoryOperationWithResultValue<DaoGetSnapshotAccountTransaction>
{
}
