namespace BudganServices.UseCases.AccountRecurringTransaction.GetTransactionsByAccount;

public interface IGetRecurringTransactionsByAccountUseCase : IBaseUseCaseWithResultValue<List<BOAccountRecurringTransaction>>
{
}
