namespace BudganInfra.Repositories.AccountTransaction.GetPageByAccount;

public interface IGetPageAccountTransactionByAccountRepoOp : IRepositoryOperationWithResultValue<DaoGetPageAccountTransaction>
{
}
